# port
server:
  port: 8088
  domain: http://10.201.11.45:8088
  servlet:
    context-path: /atv

# db
spring:
  datasource:
    url: jdbc:sqlserver://10.201.21.95;databaseName=ATVNET
    username: atvnetadm
    password: ggJ5tp?SfvAd_4@U
    hibernate.dialect: org.hibernate.dialect.SQLServer2008Dialect
    configuration:
      connectionTimeout: 30000
      idleTimeout: 600000
      maxLifetime: 1800000
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  jmx:
    enable: false
    default-domain: sync
  jackson:
    time-zone: Asia/Ho_Chi_Minh
    date-format: yyyy-MM-dd HH:mm:ss

# uploading
data.patho: C:\Dao\res\paperless\media\
data.path: C:\Dao\paperless\res\media\
data.thumb: C:\Dao\paperless\res\thumb\

# logging
logging:
  level:
    com.foxconn.fii: INFO
#        org.hibernate.SQL: DEBUG
#    org.springframework.jdbc.core.JdbcTemplate: DEBUG

#cron


batch:
  cron:
    sync:
      output-me-b04: 0 0 9 * * *
      hr-covid-b04: 0 20 13,1 * * *